spring.datasource.url=${CARD_MIZER_DB_URL:jdbc:postgresql://localhost:55432/cardmizer}
spring.datasource.username=${CARD_MIZER_DB_USERNAME:cardmizer}
spring.datasource.password=${CARD_MIZER_DB_PASSWORD:cardmizer}
spring.datasource.driver-class-name=org.postgresql.Driver
